openapi: 3.0.0
info:
  title: Bus Reservation External
  description: >-
    Bus Reservation External | Generate Client Id and Secret from
    http://ticketing.madani.com.np/admin/site-setting/client-secret |  For
    Private routes : Authorization => Bearer <token>
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: http://ticketing.madani.com.np
    description: Base URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Authentication
  - name: bus schedule
  - name: bus booking
paths:
  /api-external/token-generate:
    post:
      tags:
        - Authentication
      summary: token generate new method
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                grant_type: client_credentials
                client_id: 399ede22-e442-43ac-90b8-b6cd69962d75
                client_secret: 4oRjLF0sw8rjlD3JzfYRdOAd5g5C0xcCSAP7Pcb3
                scope: '*'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/oauth/token:
    post:
      tags:
        - Authentication
      summary: get token old method
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                grant_type: client_credentials
                client_id: 399ede22-e442-43ac-90b8-b6cd69962d75
                client_secret: 4oRjLF0sw8rjlD3JzfYRdOAd5g5C0xcCSAP7Pcb3
                scope: '*'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-list:
    get:
      tags:
        - bus schedule
      summary: bus schedule list madani request
      parameters:
        - name: route_code
          in: query
          schema:
            type: integer
          example: '1'
        - name: association_code
          in: query
          schema:
            type: integer
          example: '1'
        - name: date
          in: query
          schema:
            type: string
          example: '2080-03-12'
        - name: bus_facility_type_code
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-bus-detail:
    get:
      tags:
        - bus schedule
      summary: bus schedule bus detail
      parameters:
        - name: route_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Route Code
          example: ktmmnr100
        - name: association_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Association Code
          example: m100
        - name: date
          in: query
          schema:
            type: string
          description: Scheduled Bus Date
          example: '2080-05-31'
        - name: bus_facility_type_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Time
          example: ac100
        - name: time
          in: query
          schema:
            type: string
          description: Scheduled Bus Facility Type Code
          example: '20:00'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-schedule-bus-seats/{bus_schedule_id}:
    get:
      tags:
        - bus schedule
      summary: bus schedule bus seats by bus schedule id
      parameters:
        - name: bus_schedule_id
          in: path
          schema:
            type: integer
          required: true
          description: Scheduled Bus Schedule Id
          example: '127'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/pre-booking:
    get:
      tags:
        - bus booking
      summary: pre booking
      security:
        - bearerAuth: []
      parameters:
        - name: route_code
          in: query
          schema:
            type: string
          description: Bus Seat Name
          example: ktmmnr100
        - name: association_code
          in: query
          schema:
            type: string
          description: Bus Seat Name
          example: m100
        - name: date
          in: query
          schema:
            type: string
          description: Scheduled Bus Route Code
          example: '2080-05-31'
        - name: bus_facility_type_code
          in: query
          schema:
            type: string
          description: Scheduled Bus Association Code
          example: ac100
        - name: time
          in: query
          schema:
            type: string
          description: Scheduled Bus Date
          example: '20:00'
        - name: seat_name[]
          in: query
          schema:
            type: string
          description: Scheduled Bus Time
          example: B2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/pre-booking-timeout:
    post:
      tags:
        - bus booking
      summary: pre booking timeout
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                route_code:
                  type: string
                  description: Bus Seat Name
                  example: ktmmnr100
                association_code:
                  type: string
                  description: Bus Seat Name
                  example: m100
                date:
                  type: string
                  description: Scheduled Bus Route Code
                  example: '2080-05-31'
                bus_facility_type_code:
                  type: string
                  description: Scheduled Bus Association Code
                  example: ac100
                time:
                  type: string
                  description: Scheduled Bus Date
                  example: '20:00'
                seat_name[]:
                  type: string
                  example: KA
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-booking:
    post:
      tags:
        - bus booking
      summary: store booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                route_code: ktmmnr100
                association_code: m100
                date: '2080-05-31'
                time: '20:00'
                bus_facility_type_code: ac100
                drop_location: drop location here000
                rate: 15
                discount: 6
                contact_name: Bikash SinghTEST
                contact_phone: '98713264000'
                seat_name:
                  - B3
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/bus-booking/cancel:
    post:
      tags:
        - bus booking
      summary: cancel booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                route_code: ktmmnr100
                association_code: m100
                date: '2080-04-32'
                time: '20:00'
                bus_facility_type_code: ac100
                seat_name:
                  - x
                  - KA
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api-external/my-booking:
    get:
      tags:
        - bus booking
      summary: my booking history
      security:
        - bearerAuth: []
      parameters:
        - name: from_date
          in: query
          schema:
            type: string
          description: Departure Date From
          example: '2080-05-31'
        - name: to_date
          in: query
          schema:
            type: string
          description: Departure Date To
          example: '2080-05-31'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
